---
language: node_js
node_js:
  - "12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH

install:
  - npm install

script:
  - npm test
